version: '3'
services:
  besu-node3:
    image: hyperledger/besu:23.10.2
    hostname: besu_node3
    volumes:
      - .:/var/lib/besu/QBFT-Network

    ports:
# RPC_HTTP_PORT:8545
# RPC_WS_PORT:8546
# P2P_PORT:30303
# HTTP_GRAPHQL_PORT:8547
# HTTP_ENGINE_JSON_RPC_PORT:8550
# WS_ENGINE_JSON_RPC_PORT:8551
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 8547:8547
      - 8550:8550
      - 8551:8551
#    depends_on:
#      - prometheus  
    command: --config-file=/var/lib/besu/QBFT-Network/configNodes/node-config.toml
#    environment:
#      - PATH=/opt/besu/bin:$PATH
#      - JAVA_HOME=/opt/besu/java-19-openjdk-amd64
#      - BESU_VERSION=23.10.1-SNAPSHOT #22.1.0-RC5-SNAPSHOT
#      - NETWORK_ID=1

    networks:
      besu_network:
        ipv4_address: 172.16.0.4

networks:
  besu_network:
    name: besu_network
    driver: overlay
    external: true
