version: "3.6"
services:
  api:
    image: web3labs/epirus-free-api:latest
    environment:
      - NODE_ENDPOINT=http://besu_node1:8545
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - REINDEX_ENDPOINT=http://ingestion/reindex/
      - MONGO_DB_NAME=epirus
      - MONGO_CREATE_INDICES=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis 
      - mongodb
    networks:
      besu_network:
        ipv4_address: 172.16.0.245
  
  mongodb:
    image: mongo:5.0.8
    environment:
      - COMPOSE_HTTP_TIMEOUT=900
      - DOCKER_CLIENT_TIMEOUT=900
    entrypoint: mongod --bind_ip "0.0.0.0"
    networks:
      besu_network:
        ipv4_address: 172.16.0.244

  redis:
    image: redis
    restart: unless-stopped
    container_name: redis
    networks:
      besu_network:
        ipv4_address: 172.16.0.243

  web:
    image: web3labs/epirus-free-web:latest
    environment:
      - API_URL=/api
      - DISPLAY_NETWORK_TAB=true
    depends_on:
      - api
    networks:
      besu_network:
        ipv4_address: 172.16.0.242
  
  ingestion:
    image: web3labs/epirus-free-ingestion:latest
    environment:
      - NODE_ENDPOINT=http://besu_node1:8545
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=epirus
    depends_on:
      - mongodb
    networks:
      besu_network:
        ipv4_address: 172.16.0.241
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./5xx.html:/www/error_pages/5xx.html
    ports:
      - ${PORT:-80}:80
    depends_on:
      - api
      - web
    networks:
      besu_network:
        ipv4_address: 172.16.0.240
        

networks:
  besu_network:
    name: besu_network
    driver: overlay
    external: true

